### ISSUE TITLE
Dataset of FMCW lidar

### ISSUE THREAD

**Issue by wwtinwhu** [aevainc/Doppler-ICP#1]
Excellent work! Is there any plan to open source the experimental data? Or is there an open source dataset of related FMCW lidars?

**Comment by heethesh** [comment]
@wwtinwhu thanks, as of now, our plan is to release the source for the FMCW LiDAR plug-in we built in CARLA simulation. Please watch this repo: https://github.com/aevainc/carla for updates.

**Comment by wwtinwhu** [comment]
> @wwtinwhu thanks, as of now, our plan is to release the source for the FMCW LiDAR plug-in we built in CARLA simulation. Please watch this repo: https://github.com/aevainc/carla for updates.

ok,thanks!

**Comment by AlphaHot** [comment]
@heethesh hello, and on what day will the entire code be published?

**Comment by heethesh** [comment]
@AlphaHot should be very soon, most likely we'll release it early this coming week.

**Comment by heethesh** [comment]
Please check the updated [README](https://github.com/aevainc/Doppler-ICP#readme) now.
