### ISSUE TITLE
Aeve AeriesII ROS driver support ?

### ISSUE THREAD

**Issue by kahowang** [aevainc/Doppler-ICP#6]
Hello, nice job.  
May I ask if you provide ROS drivers for Aeve AeriesII ?
Looking for your reply soon ~

**Comment by heethesh** [comment]
Hi @kahowang, certainly, please reach out to me at heethesh@aeva.ai and we can share our ROS API with you.

**Comment by kahowang** [comment]
Hello, heethesh

Thank you very much for your reply. In addition, I would like to ask whether the sample dataset provided in the Doppler-ICP repo which is containing 10 *.bin files. Is this the real world collected data or the simulation data of carla ？

Looking for your reply soon ~

Kaho

**Comment by heethesh** [comment]
They are simulated sequences from CARLA.
