### ISSUE TITLE
sample data can't be read correctly

### ISSUE THREAD

**Issue by HoumoLudens** [aevainc/Doppler-ICP#7]
Very impressive work, and I just try to reproduce the result in the paper.
But when I try to run `python run.py --sequence sample -o OUTPUT_DIR` , I got the error:

> PID: [1024933]
> Loaded sequence: sample with 10 scans
> Loaded 10 poses from ref_poses.txt (0.90 secs)
> Processing:  11%|███████████████                                                                                                                        | 1/9 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "run.py", line 234, in <module>
>     run(args)
>   File "run.py", line 104, in run
>     source = utils.load_point_cloud(pcd_files[i])
>   File "/home/zhiyuan/share_folder/DICP-verificarion/Doppler-ICP/scripts/utils.py", line 166, in load_point_cloud
>     data = np.fromfile(filename, dtype=np.float32).reshape(-1, 4)
> ValueError: cannot reshape array of size 33 into shape (4)

It seems that the sample data's size is not correct. Just want confirm is the sample data is uploaded correctly, or is there any step I missed(I basically just followed the readme...)

Hope for your help !

**Comment by heethesh** [comment]
Can you please print out `data.shape`? I just tried it and it seems fine. I see `(78539, 4)` as the shape. It's quite odd you only have 33 elements in your array. Can you please try downloading the data again?

**Comment by WCH945** [comment]
I got the same problem

**Comment by JinRhee** [comment]
Ran into same issue: the data shape before numpy attempts to reshape it is (33,), and `hexdump` shows the binary files having 33 elements (00001.bin).
Works fine with other provided datasets though.
![Screenshot from 2024-07-23 16-46-48](https://github.com/user-attachments/assets/4595c10c-8551-4a96-8b16-186489273b0d)

**Comment by heethesh** [comment]
GitHub shows this when I open the file on the web browser:
```
version https://git-lfs.github.com/spec/v1
oid sha256:630576ce64156f76cc896696fe47aefdb9bde1f0f12e4eb24e13017aabd6f528
size 1256624
```

1256624 / (4 (float32) * 4 (XYZV)) = 78,539 rows or points.

I'm really not sure what's going on here. Have you tried `git lfs pull`? I'm not able to reproduce this issue.

I wonder if those 33 bytes are just some Git LFS pointers and not the actual data.

**Comment by JinRhee** [comment]
Installing `git-lfs` and pulling as you said solved the issue! Sample sequence now runs fine
Thanks :)
